### ISSUE TITLE
Allow loops in graphs!

### ISSUE THREAD

**Issue by timgalvin** [danielgmyers/flux-swf-client#134]
😜

**Comment by danielgmyers** [comment]
Thanks Tim ;)

As Tim is aware, because we discussed it before he posted this issue, I have no plans to add support for loops in Flux absent a compelling use case that can't be easily solved with just running the workflow multiple times, or doing the loop inside the implementation of a single step.

For anyone wondering, the main reasons are:
1) The [25k event limit](https://github.com/danielgmyers/flux-swf-client/issues/48) in SWF means loops can't have too many iterations, so I want to encourage design patterns that avoid this limit. (This is a problem for partitioned steps with many partitions, too.)
2) I designed Flux to help users construct workflows that are easy to understand. Loops make the graph significantly more complicated, especially when you add branches into the mix.

If anyone has a compelling use case for loops, please feel free to reopen this issue with details!
